### ISSUE TITLE
symfony 4.0@dev

### ISSUE THREAD

**Issue by angular-tools** [jmikola/WildcardEventDispatcher#10]
I'm trying to use this with "symfony/routing": "^4.0@dev". But composer fails and gives an error.

Is there a workaround for it?

Thanks

**Comment by jmikola** [comment]
https://github.com/jmikola/WildcardEventDispatcher/commit/0300cbb1a50a27529ea7e851d7922d235b4ce543 added `^3.0` to the Symfony package requirements; however, 4.0 is not yet released so I'd be hesitant to incorporate `^4.0` into the requirement lest there a BC breaks in the EventDispatcher component.

In the meantime, I suppose you could fork this and relax the dependency on your own.

**Comment by caseyamcl** [comment]
Now that Symfony 4 is out, can the dependency be updated?  Thanks!

**Comment by jmikola** [comment]
@caseyamcl: Would you mind submitting a PR to this library and the [bundle](https://github.com/jmikola/JmikolaWildcardEventDispatcherBundle)? I imagine it may be as simple as add ` || ^4.0` to the Symfony package requirements; however, I don't have a Symfony 4 app available to test and would not want to blindly tag a compatibility release on the off chance the test suites in the library/bundle missed something.


Can you submit

**Comment by caseyamcl** [comment]
Sure thing!  I created PR #11 .. Additional comments in there.

**Comment by jmikola** [comment]
https://github.com/jmikola/WildcardEventDispatcher/pull/11 has been merged and [1.1.1](https://github.com/jmikola/WildcardEventDispatcher/releases/tag/1.1.1) is tagged. The bundle will be updated shortly.
