### ISSUE TITLE
php 7.3 support

### ISSUE THREAD

**Issue by Misosooup** [jmikola/WildcardEventDispatcher#15]
Hi there,

PHP7.3 has added `#` as a special character. This needs to be escaped as part of the $replacements in ListenerPattern. 

https://www.php.net/manual/en/function.preg-quote.php

**Comment by jmikola** [comment]
I believe you already found a solution, but this should be addressed by https://github.com/jmikola/WildcardEventDispatcher/pull/14.

**Comment by Misosooup** [comment]
Yes i saw that after raising this issue. Thanks.
